-   id: commitlint-azure-pipelines
    name: Check commit messages on Azure Pipelines PRs
    description: Lint all relevant commits for a change or PR on Azure Pipelines
    entry: commitlint-azure-pipelines
    language: node
    always_run: true
    pass_filenames: false
    require_serial: true
    additional_dependencies: ["commitlint-azure-pipelines-cli@1.0.5"]
    minimum_pre_commit_version: '0'
